# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv ramdisk_addr_r 0x64000000
setenv load_addr 0x600f0000
setenv overlay_error false

# Default values (only if not set by armbianEnv.txt)
if test -z "${verbosity}"; then setenv verbosity 1; fi
if test -z "${console}"; then setenv console ttyS1,115200; fi
if test -z "${bootlogo}"; then setenv bootlogo false; fi
if test -z "${rootfstype}"; then setenv rootfstype ext4; fi
if test -z "${docker_optimizations}"; then setenv docker_optimizations on; fi
if test -z "${mtdparts}"; then setenv mtdparts rk29xxnand:0x00002000@0x00002000(uboot),0x00002000@0x00004000(trust),0x00010000@0x00006000(boot),-@0x00016000(root); fi
if test -z "${overlay_prefix}"; then setenv overlay_prefix rk3128; fi

# If gpio3 pin 25 is 0, reset into MASKROM
if gpio input D25; then
    echo "Resetting into MASKROM mode..."
    mw.l 0x110005c8 0xEF08A53C 1
    reset
fi

echo "Boot script loaded from ${devtype} ${devnum}"

if test "${devtype}" = "rknand"; then
    setenv bootpart "${devnum}:1"
    echo "Using ext4load for RKNAND boot files from ${devtype} ${bootpart}"
else
    setenv bootpart "${devnum}"
fi

# Load armbianEnv.txt if present
if test -e ${devtype} ${bootpart} ${prefix}armbianEnv.txt; then
    if test "${devtype}" = "rknand"; then
        ext4load ${devtype} ${bootpart} ${load_addr} ${prefix}armbianEnv.txt
    else
        load ${devtype} ${bootpart} ${load_addr} ${prefix}armbianEnv.txt
    fi
    env import -t ${load_addr} ${filesize}
fi

# Root device auto detection (only if not defined in armbianEnv.txt)
if test -z "${rootdev}"; then

    if test "${devtype}" = "mmc"; then
        echo "Detected MMC boot (device ${devnum})"
        setenv rootdev "/dev/mmcblk${devnum}p1"
    fi

    if test "${devtype}" = "usb"; then
        echo "Detected USB boot"
        setenv rootdev "/dev/sda1"
    fi

    if test "${devtype}" = "rknand"; then
        echo "Detected NAND boot"
        setenv rootdev "/dev/rknand_root"
    fi

fi

echo "[DEBUG] ========= Root device: ${rootdev}"

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

# get PARTUUID if booted from MMC
if test "${devtype}" = "mmc"; then
    part uuid mmc ${devnum}:1 partuuid
fi

if test "${bootlogo}" = "true"; then
    setenv consoleargs "bootsplash.bootfile=bootsplash.armbian ${consoleargs}"
fi

setenv bootargs "uart8250,mmio32,0x20064000 earlyprintk  console=${console} loglevel=${verbosity} ignore_loglevel earlycon root=${rootdev} rootwait rw rootfstype=${rootfstype} ${consoleargs} consoleblank=0  ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs} mtdparts=${mtdparts}"

if test "${docker_optimizations}" = "on"; then
    setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"
fi

# Load initrd
echo "[DEBUG] ========= Loading initrd from: ${devtype} ${bootpart} ${ramdisk_addr_r} ${prefix}uInitrd"
if test "${devtype}" = "rknand"; then
    ext4load ${devtype} ${bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
else
    load ${devtype} ${bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
fi

# Load kernel
echo "[DEBUG] ========= Loading kernel from: ${devtype} ${bootpart} ${kernel_addr_r} ${prefix}zImage"
if test "${devtype}" = "rknand"; then
    ext4load ${devtype} ${bootpart} ${kernel_addr_r} ${prefix}zImage
else
    load ${devtype} ${bootpart} ${kernel_addr_r} ${prefix}zImage
fi

# Load device tree
echo "[DEBUG] ========= Loading dtb from: ${devtype} ${bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}"
if test "${devtype}" = "rknand"; then
    ext4load ${devtype} ${bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
    load ${devtype} ${bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fi
fdt addr ${fdt_addr_r}
fdt resize 65536

# Apply kernel overlays

# For USB OTG support, either usb-otg-host or usb-otg-peripheral overlay must be applied. If none of them is set, apply usb-otg-host by default.
setenv otg_overlay_set false
for overlay_file in ${overlays}; do
    if test "${overlay_file}" = "usb-otg-host"; then setenv otg_overlay_set true; fi
    if test "${overlay_file}" = "usb-otg-peripheral"; then setenv otg_overlay_set true; fi
done

if test "${otg_overlay_set}" = "false"; then
    if test -z "${overlays}"; then
        setenv overlays "usb-otg-host"
    else
        setenv overlays "${overlays} usb-otg-host"
    fi
fi

for overlay_file in ${overlays}; do
    if test "${devtype}" = "rknand"; then
        if ext4load ${devtype} ${bootpart} ${load_addr} ${prefix}dtb/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
            echo "[DEBUG] ========= Applying kernel overlay ${overlay_prefix}-${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error true
        fi
    else
        if load ${devtype} ${bootpart} ${load_addr} ${prefix}dtb/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
            echo "[DEBUG] ========= Applying kernel overlay ${overlay_prefix}-${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error true
        fi
    fi
done

# Apply user overlays
for overlay_file in ${user_overlays}; do
    if test "${devtype}" = "rknand"; then
        if ext4load ${devtype} ${bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
            echo "[DEBUG] ========= Applying user overlay ${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error true
        fi
    else
        if load ${devtype} ${bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
            echo "[DEBUG] ========= Applying user overlay ${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error true
        fi
    fi
done

# Fixup scripts
if test "${overlay_error}" = "true"; then
    echo "Overlay error, restoring original DT"
    if test "${devtype}" = "rknand"; then
        ext4load ${devtype} ${bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
    else
        load ${devtype} ${bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
    fi
else
    if test "${devtype}" = "rknand"; then
        if ext4load ${devtype} ${bootpart} ${load_addr} ${prefix}dtb/overlay/${overlay_prefix}-fixup.scr; then
            echo "[DEBUG] ========= Applying fixup script"
            source ${load_addr}
        fi

        if test -e ${devtype} ${bootpart} ${prefix}fixup.scr; then
            ext4load ${devtype} ${bootpart} ${load_addr} ${prefix}fixup.scr
            echo "[DEBUG] ========= Applying user fixup script"
            source ${load_addr}
        fi
    else
        if load ${devtype} ${bootpart} ${load_addr} ${prefix}dtb/overlay/${overlay_prefix}-fixup.scr; then
            echo "[DEBUG] ========= Applying fixup script"
            source ${load_addr}
        fi

        if test -e ${devtype} ${bootpart} ${prefix}fixup.scr; then
            load ${devtype} ${bootpart} ${load_addr} ${prefix}fixup.scr
            echo "[DEBUG] ========= Applying user fixup script"
            source ${load_addr}
        fi
    fi
fi

echo "[DEBUG] ========= Now trying to boot using bootz."
echo "[DEBUG] ========= Boot arg is: ${bootargs}"
bootz ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Always remember to use mkimage shipped with this U-boot version. Recompile with:
# mkimage -A arm -T script -C none -n "Armbian boot script for RK3128 by https://chieunhatnang.de" -d boot.cmd boot.scr
